version: "3"

services:
  web:
    build: ./project-phone-book-front
    container_name: phone-book-front
    ports:
      - 3000:3000
    links:
      - server
  server:
    build: ./project-phone-book-api
    container_name: phone-book-api
    environment:
      - API_URL=localhost
      - API_PORT=3010
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_NAME=postgres
    ports:
      - 3010:3010
    links:
      - postgres-db
  postgres-db:
    image: "postgres:9.6-alpine"
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345